### ISSUE TITLE
Would it work with webpack 1.15.0?

### ISSUE THREAD

**Issue by Restuta** [niieani/chunk-splitting-plugin#5]
Getting an error on my project, but not sure if it's because Webpack 1.15.0 or not.

```javascript
const async = !chunk.isInitial()
                         ^
TypeError: chunk.isInitial is not a function
```

**Comment by niieani** [comment]
I'm sorry, but no. The latest version only supports Webpack 3.0, while the older, v1.1 supports Webpack 2. Feel free to fork and try to make it work with Webpack 1 though.

**Comment by Restuta** [comment]
Got it, thanks @niieani
